remote_theme: "pages-themes/cayman"

plugins:
  - jekyll-remote-theme

defaults:
  - scope:
      path: ""
      type: "pages-themes/cayman"
    values:
      layout: "default"
      title: "GDP Data Visualization: Unveiling Global Economic Insightss"
      description: "Your Page Description"

markdown: kramdown

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - requirements.txt
  - _config.yml

include:
  - CNAME

permalink: pretty

baseurl: "/<GDP-Data-Analysis>"
